<?php

namespace Sprint\Migration;

use Sprint\Migration\Exceptions\HelperException;

class BD902_20250217161925 extends Version
{
    protected $author = "V.Andreev";

    protected $description = "Добавление полей сделок: Топливо. Какой договор нужен клиенту, Топливо. Анкета должной осмотрительности, Топливо. Финансовая отчетность. Для ИП";

    protected $moduleVersion = "4.15.1";

    /**
     * @return bool
     * @throws HelperException
     */
    public function up(): bool
    {
        $helper = $this->getHelperManager();
        $helper->UserTypeEntity()->saveUserTypeEntity([
            'ENTITY_ID' => 'CRM_DEAL',
            'FIELD_NAME' => 'UF_CRM_DEAL_CONTRACT_TYPE_FUEL',
            'USER_TYPE_ID' => 'enumeration',
            'XML_ID' => '',
            'SORT' => '100',
            'MULTIPLE' => 'Y',
            'MANDATORY' => 'N',
            'SHOW_FILTER' => 'N',
            'SHOW_IN_LIST' => 'Y',
            'EDIT_IN_LIST' => 'Y',
            'IS_SEARCHABLE' => 'N',
            'SETTINGS' => [
                'DISPLAY' => 'CHECKBOX',
                'LIST_HEIGHT' => 1,
                'CAPTION_NO_VALUE' => '',
                'SHOW_NO_VALUE' => 'Y',
            ],
            'EDIT_FORM_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Какой договор нужен клиенту?',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'LIST_COLUMN_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Какой договор нужен клиенту?',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'LIST_FILTER_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Какой договор нужен клиенту?',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'ERROR_MESSAGE' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => '',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'HELP_MESSAGE' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => '',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'ENUM_VALUES' => [
                0 => [
                    'VALUE' => 'Татнефть',
                    'DEF' => 'N',
                    'SORT' => '100',
                    'XML_ID' => 'TATNEFT',
                ],
                1 => [
                    'VALUE' => 'ЭТР',
                    'DEF' => 'N',
                    'SORT' => '200',
                    'XML_ID' => 'ETR',
                ],
            ],
        ]);
        $helper->UserTypeEntity()->saveUserTypeEntity([
            'ENTITY_ID' => 'CRM_DEAL',
            'FIELD_NAME' => 'UF_CRM_DEAL_DDQ_FUEL',
            'USER_TYPE_ID' => 'file',
            'XML_ID' => '',
            'SORT' => '100',
            'MULTIPLE' => 'Y',
            'MANDATORY' => 'N',
            'SHOW_FILTER' => 'N',
            'SHOW_IN_LIST' => 'Y',
            'EDIT_IN_LIST' => 'Y',
            'IS_SEARCHABLE' => 'N',
            'SETTINGS' => [
                'SIZE' => 20,
                'LIST_WIDTH' => 0,
                'LIST_HEIGHT' => 0,
                'MAX_SHOW_SIZE' => 0,
                'MAX_ALLOWED_SIZE' => 0,
                'EXTENSIONS' => [],
                'TARGET_BLANK' => 'Y',
            ],
            'EDIT_FORM_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Анкета должной осмотрительности',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'LIST_COLUMN_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Анкета должной осмотрительности',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'LIST_FILTER_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Анкета должной осмотрительности',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'ERROR_MESSAGE' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => '',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'HELP_MESSAGE' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => '',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
        ]);
        $helper->UserTypeEntity()->saveUserTypeEntity([
            'ENTITY_ID' => 'CRM_DEAL',
            'FIELD_NAME' => 'UF_CRM_DEAL_IP_FINANCIAL_STATEMENT_FUEL',
            'USER_TYPE_ID' => 'file',
            'XML_ID' => '',
            'SORT' => '100',
            'MULTIPLE' => 'Y',
            'MANDATORY' => 'N',
            'SHOW_FILTER' => 'N',
            'SHOW_IN_LIST' => 'Y',
            'EDIT_IN_LIST' => 'Y',
            'IS_SEARCHABLE' => 'N',
            'SETTINGS' => [
                'SIZE' => 20,
                'LIST_WIDTH' => 0,
                'LIST_HEIGHT' => 0,
                'MAX_SHOW_SIZE' => 0,
                'MAX_ALLOWED_SIZE' => 0,
                'EXTENSIONS' => [],
                'TARGET_BLANK' => 'Y',
            ],
            'EDIT_FORM_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Финансовая отчетность. Для ИП',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'LIST_COLUMN_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Финансовая отчетность. Для ИП',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'LIST_FILTER_LABEL' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => 'Топливо. Финансовая отчетность. Для ИП',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'ERROR_MESSAGE' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => '',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
            'HELP_MESSAGE' => [
                'br' => '',
                'de' => '',
                'en' => '',
                'fr' => '',
                'hi' => '',
                'id' => '',
                'it' => '',
                'ja' => '',
                'la' => '',
                'ms' => '',
                'pl' => '',
                'ru' => '',
                'sc' => '',
                'tc' => '',
                'th' => '',
                'tr' => '',
                'ua' => '',
                'vn' => '',
            ],
        ]);
        return true;
    }

    /**
     * @throws HelperException
     */
    public function down(): bool
    {
        $helper = $this->getHelperManager();

        $helper->UserTypeEntity()->deleteUserTypeEntitiesIfExists('CRM_DEAL', [
            'UF_CRM_DEAL_CONTRACT_TYPE_FUEL',
            'UF_CRM_DEAL_DDQ_FUEL',
            'UF_CRM_DEAL_IP_FINANCIAL_STATEMENT_FUEL',
        ]);

        return true;
    }
}
